# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke_man_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_address',
            field=models.EmailField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
