# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke_man_app', '0002_auto_20160411_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songqueue',
            name='party',
        ),
    ]
