# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke_man_app', '0003_auto_20160401_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='song',
            field=models.ManyToManyField(to='karaoke_man_app.Song'),
        ),
    ]
