# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke_man_app', '0003_remove_party_theme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='Queue',
        ),
    ]
