# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke_man_app', '0003_location_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='desription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='party_name',
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
    ]
