# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke_man_app', '0004_auto_20160414_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='karaoke_man_app.City'),
            preserve_default=False,
        ),
    ]
