# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke_man_app', '0004_auto_20160408_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='singer_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
