# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke_man_app', '0006_auto_20160414_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='city',
        ),
    ]
