# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke_man_app', '0007_remove_party_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='songqueue',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
