# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke_man_app', '0008_songqueue_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='party_creator',
            field=models.BooleanField(default=False),
        ),
    ]
