# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke_man_app', '0009_attendee_party_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='party_creator',
        ),
    ]
