# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke_man_app', '0010_remove_attendee_party_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songqueue',
            name='attendees',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='karaoke_man_app.Attendee'),
        ),
    ]
